### ISSUE TITLE
module not idempotent with sp_inact=-1

### ISSUE THREAD

**Issue by angystardust** [lqueryvg/ansible-role-chage#5]
Module doesn't seem to respect the idempotency features of ansible when invoked with the `sp_inact` parameter set to -1 (useful to remove an account's inactivity)
In other words, every time I run an ad-hoc command using your module, it produces a change even if the configuration of the user is already applied:

```
[root@ansible-master ]#  ansible localhost -m chage -a 'user=myuser sp_inact=-1'
localhost | SUCCESS => {
    "changed": true, 
    "shadow": {
        "sp_expire": "", 
        "sp_flag": "", 
        "sp_inact": "-1", 
        "sp_lstchg": "16973", 
        "sp_max": "99999", 
        "sp_min": "0", 
        "sp_nam": "myuser", 
        "sp_pwd": "XXXX", 
        "sp_warn": "7"
    }
}

[root@ansible-master ]#  ansible localhost -m chage -a 'user=myuser sp_inact=-1'
localhost | SUCCESS => {
    "changed": true, 
    "shadow": {
        "sp_expire": "", 
        "sp_flag": "", 
        "sp_inact": "-1", 
        "sp_lstchg": "16973", 
        "sp_max": "99999", 
        "sp_min": "0", 
        "sp_nam": "myuser", 
        "sp_pwd": "XXXX", 
        "sp_warn": "7"
    }
}

```

**Comment by lqueryvg** [comment]
fixed

**Comment by angystardust** [comment]
Wow! That was so blazing fast! Thank you @lqueryvg !

**Comment by lqueryvg** [comment]
@angystardust, you should be aware that while testing I noticed some rather strange behaviour with chage and date strings. For example you can give it some strange looking date strings with sometimes different behaviour on different flavours of Linux.

E.g. `chage -E wibble  testuser` deletes the expire field on Centos5 but is rejected with an "invalid date" error on Ubuntu 14.04.

`chage -E 11111-1111-11 testuser` is accepted on both and results in the value `3372475`.

My module only really handles yyyy-mm-dd at the moment. I'm not sure how many of the various nuances of chage I need to try and replicate.

What are your thoughts ?

**Comment by angystardust** [comment]
You can find my thoughts at https://github.com/lqueryvg/ansible-role-chage/issues/3#issuecomment-234716248 :smile:
