### ISSUE TITLE
Not prompting for password (ignored)

### ISSUE THREAD

**Issue by BarbzYHOOL** [lqueryvg/ansible-role-chage#8]
I reset the password, then I log from root with "su user" but it says this

```
You are required to change your password immediately (root enforced)
su: Authentication token is no longer valid; new one required
(Ignored)
```

And it doesn't prompt me for a password. I suppose it's not really related to the role itself but if you have any idea why it happens :(

**Comment by lqueryvg** [comment]
My guess is that your root user has expired.

**Comment by BarbzYHOOL** [comment]
I don't know, when I connected with normal SSH as the user, it prompted me...
